### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by tonybruess** [bung87/vscode-rails#76]
```
2023-01-25 07:39:23.728 [error] Activating extension bung87.rails failed due to an error:
2023-01-25 07:39:23.728 [error] Error: Cannot find module 'compact-prefix-tree/cjs'
Require stack:
- /Users/tony/.vscode/extensions/bung87.rails-0.17.8/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Users/tony/.vscode/extensions/bung87.rails-0.17.8/dist/extension.js:1596:50)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at d.pb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:63164)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
```

**Comment by nelsonjma** [comment]
Hello, 

I installed the package compact-prefix-tree to solve the same issue, I had to use sudo because my node installation is at the system level and not in local user.

`sudo npm install -g compact-prefix-tree`

hope this helps.

**Comment by rubensa** [comment]
Same problem here

```bash
2024-10-18 11:15:02.823 [error] Activating extension bung87.rails failed due to an error:
2024-10-18 11:15:02.824 [error] Error: Cannot find module 'compact-prefix-tree/cjs'
Require stack:
- /home/user/.vscode-server/extensions/bung87.rails-0.17.8/dist/extension.js
- /vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
	at t._resolveFilename (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:166:22704)
	at Module._load (node:internal/modules/cjs/loader:986:27)
	at e._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (/home/user/.vscode-server/extensions/bung87.rails-0.17.8/dist/extension.js:1596:50)
	at Module._compile (node:internal/modules/cjs/loader:1358:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
	at Module.load (node:internal/modules/cjs/loader:1208:32)
	at Module._load (node:internal/modules/cjs/loader:1024:12)
	at e._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1233:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///vscode/vscode-server/bin/linux-arm64/384ff7382de624fb94dbaf6da11977bba1ecd427/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
```

Running `npm install -g compact-prefix-tree` didn't solve the problem.  In any case, I think this should not be needed at all and the package should be installed by the extension itself.

Trying to figure out the problem I just went to extension installation directory (_~/.vscode-server/extensions/bung87.rails-0.17.8_) and manually run:

```bash
$ npm install
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated vscode-test@1.6.1: This package has been renamed to @vscode/test-electron, please update to the new name
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2024-10-18T09_41_42_335Z-debug.log
```

So here is the problem!!  **alias** is not available on **npm** versions lower than **[v6.9.0](https://github.com/npm/cli/releases/tag/v6.9.0)**, despite **yarn** used to have this functionality for a long time (which looks is the one used to develop this extension but I think **VSCode** runs **npm** on extension installation).

I then run:

```bash
$ npm install yarn

> yarn@1.22.22 preinstall /home/user/.vscode-server/extensions/bung87.rails-0.17.8/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

npm notice created a lockfile as package-lock.json. You should commit this file.
+ yarn@1.22.22
added 1 package and audited 1 package in 3.669s
found 0 vulnerabilities
```

and:

```bash
$ node_modules/.bin/yarn install --ignore-engines
yarn install v1.22.22
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @rollup/plugin-commonjs > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @rollup/plugin-commonjs > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @rollup/plugin-commonjs > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
warning tslint > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning vscode-test@1.6.1: This package has been renamed to @vscode/test-electron, please update to the new name
warning vscode-test > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning vscode-test > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning vscode-test > unzipper > fstream@1.0.12: This package is no longer supported.
warning vscode-test > unzipper > fstream > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
warning vscode-test > unzipper > fstream > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.34s.
```

Reload window and voila!  Now it's working as expected.

**Comment by rubensa** [comment]
Despite previous comment worked, looks like I was mistaken and **VSCode** does not install any dependencies.  The dependencies should be bundled with the extension itself.

I just tried downgrading form **v0.17.8** to **v.0.17.7** and this version worked without problem.

It seems that something was missing in the building process of latest version and some dependencies were not included.  Checking _dist/extension.js_ file size from **v0.17.8** (**880886**) and **v0.17.7** (**1305216**) might confirm the problem as **v0.17.7** is much bigger than **v0.17.8**.

**Comment by bung87** [comment]
this may be solved after 0.22.0 released, if you guys have any problems please lmk

**Comment by rubensa** [comment]
@bung87 Just checked and latest version (v0.22.0) seems to be working as expected.  Thanks for fixing this.

**Comment by rubensa** [comment]
@bung87 I do not why, but looks like latest version (v0.22.0) makes VSCode unresponsive, al least using it in a Docker DevContainer.  

When I open a rb file and, for example, try to navigate to a parent class, I keep seeing many Dev Containers log messages like:

> [870774 ms] Port forwarding 55982 > 43955 > 43955: Local close
[870812 ms] Port forwarding 55982 > 43955 > 43955 stderr: Remote stdin close
[870852 ms] Port forwarding 55982 > 43955 > 43955 terminated by extension (closed) with code 0 and signal null.
[872109 ms] Port forwarding connection from 59734 > 43955 > 43955 in the container.
[872112 ms] Start: Run in container: /home/user/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node -e 
[872573 ms] Port forwarding 59734 > 43955 > 43955 stderr: Connection established
[872648 ms] [09:18:16] [127.0.0.1][64b581db][ExtensionHostConnection] The client has reconnected.

that makes me think the extension, somehow, saturates the communication among client and server processes (as, then, I can't save files or have responses from other extensions).

I can also see an VSCode server node process with a 100% CPU usage.

This does not happen with version v0.17.7.
